{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "069f0de5-a013-48db-bd9b-c4b4ff613c49",
   "metadata": {},
   "outputs": [],
   "source": [
    "Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions\n",
    "Ans:When creating a custom exception, we need to inherit from the Exception class because it provides the basic functionality required by all exceptions\n",
    ", such as message passing and stack trace tracking. Inheriting from Exception ensures that the custom exception behaves like a standard exception and \n",
    "can be caught by a try-catch block, logged, or handled in a consistent way with other exceptions in the codebase. It also allows the custom exception to\n",
    "leverage any additional features or functionality provided by the Exception class or any of its subclasses."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8333650-3876-45d5-b034-0f6cec6f12cd",
   "metadata": {},
   "outputs": [],
   "source": [
    " # Write a python program to print Python Exception Hierarchy.\n",
    "import logging\n",
    "logging.basicConfig(filename= \"test.log\",level = logging.INFO)\n",
    "def print_exception_hierarchy(exceptions, level=0):\n",
    "    for exception in exceptions:\n",
    "        print('\\t' * level, exception.__name__)\n",
    "        logging.info(print_exception_hierarchy(exception.__subclasses__(), level+1))\n",
    "\n",
    "print_exception_hierarchy([Exception])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c950517a-16dd-469c-b058-e31b3b62a7fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# What errors are defined in the ArithmeticError class? Explain any two with an example\n",
    "# The ArithmeticError class is a built-in Python exception class that serves as the base class for several other built-in \n",
    "# exception classes that represent specific types of arithmetic errors. Some of the exceptions that are defined in the ArithmeticError\n",
    "# class are:\n",
    "\n",
    "#     FloatingPointError: This exception is raised when a floating-point calculation results in an error.\n",
    "#     For example, when dividing by zero in a floating-point operation.\n",
    "\n",
    "#     OverflowError: This exception is raised when a calculation exceeds the maximum representable value of a numeric data type.\n",
    "\n",
    "#     ZeroDivisionError: This exception is raised when an attempt is made to divide a number by zero.\n",
    "\n",
    "#     UnderflowError: This exception is raised when a calculation results in a value that is too small to be represented by a numeric data type.\n",
    "\n",
    "#     ArithmeticError: This is the base class for all arithmetic exceptions.\n",
    "\n",
    "# All of these exceptions are related to arithmetic operations and represent different types of errors that can occur during such operations.\n",
    "import logging\n",
    "logging.basicConfig(filename= \"test.log\",level = logging.ERROR)\n",
    "try:\n",
    "    result=5/0\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"Zerodivision Error Occor\")\n",
    "\n",
    "# FloatingPointError\n",
    "import math\n",
    "try:\n",
    "    x = math.sqrt(-1)\n",
    "except FloatingPointError as e:\n",
    "    logging.error(\"Caught FloatingPointError:\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "317a194a-d61f-44bf-9844-8cb9b8b5da98",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Why LookupError class is used? Explain with an example KeyError and IndexError\n",
    "# Ans :The LookupError class is a built-in Python exception class that serves as the base class for several other\n",
    "# built-in exception classes that represent errors related to key or index lookups in data structures.\n",
    "import logging\n",
    "logging.basicConfig(filename= \"test.log\",level = logging.ERROR)\n",
    "# example:Keyerror\n",
    "try:\n",
    "    my_dict = {\"apple\": 1, \"banana\": 2, \"orange\": 3}\n",
    "    my_dict[\"grape\"]\n",
    "except KeyError as e:\n",
    "    logging.error(\"KeyError{}\".format(e))\n",
    "# IndexError\n",
    "try:\n",
    "    my_list = [1, 2, 3]\n",
    "    my_list[3]\n",
    "except IndexError as e:\n",
    "    logging.error(\"Indexerror{}\".format(e))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "e3ee4f5f-84c6-4b81-bbe6-a68a9b8ca0f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Explain ImportError. What is ModuleNotFoundError?\n",
    "# ImportError is a built-in Python exception class that is raised when there is an error while importing a module. \n",
    "# This can happen when a module does not exist, cannot be found in the search path, or when there is a syntax error in the module being imported.\n",
    "# ModuleNotFoundError is a subclass of ImportError that was introduced in Python 3.6. It is raised when a module could not \n",
    "# be found in the search path. In other words, when the Python interpreter is unable to locate the module that is being imported.\n",
    "import logging\n",
    "logging.basicConfig(filename= \"test.log\",level = logging.ERROR)\n",
    "# This will raise a ModuleNotFoundError\n",
    "try:\n",
    "    import my_module\n",
    "except ModuleNotFoundError as e:\n",
    "    logging.error(\"Caught ModuleNotFoundError:{}\" .format(e))\n",
    "\n",
    "# This will raise an ImportError\n",
    "try:\n",
    "    import syntax_error_module\n",
    "except ImportError as e:\n",
    "    logging.error(\"Caught ImportError:{}\" .format(e))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8a458b3f-9131-4c15-abd2-b9378b644436",
   "metadata": {},
   "outputs": [],
   "source": [
    "# List down some best practices for exception handling in python\n",
    "import logging\n",
    "logging.basicConfig(filename = \"test.log\" , level = logging.ERROR)\n",
    "#use always a specific exception\n",
    "try :\n",
    "    10/0\n",
    "except Exception as e :\n",
    "    logging.error(\"I am handling error:{}\".format(e))\n",
    "#print always a proper message \n",
    "try :\n",
    "    10/0\n",
    "except ZeroDivisionError as e :\n",
    "    logging.error(\"i am trying to handle a zerodivision error\"  .format(e))\n",
    "#always try to log your error\n",
    "import logging\n",
    "logging.basicConfig(filename = \"test.log\" , level = logging.ERROR)\n",
    "try :\n",
    "    10/0\n",
    "except ZeroDivisionError as e :\n",
    "    logging.error(\"i am trying to handle a zerodivision error {} \".format(e) )\n",
    "#alwyas avoid to write a multiple exception handling \n",
    "try :\n",
    "    10/0\n",
    "except FileNotFoundError as e : \n",
    "    logging.error(\"i am handling file not found  {} \".format(e) )\n",
    "except AttributeError as e : \n",
    "    logging.error(\"i am handling Attribute erro  {} \".format(e) )\n",
    "except ZeroDivisionError as e :\n",
    "    logging.error(\"i am trying to handle a zerodivision error {} \".format(e) )\n",
    "#Document all the error \n",
    "#cleanup all the resources\n",
    "try :\n",
    "    with open(\"test1.txt\" , 'w') as f :\n",
    "        f.write(\"this is my data to file \" )\n",
    "except FileNotFoundError as e : \n",
    "    logging.error(\"i am handling file not found  {} \".format(e) )\n",
    "finally :\n",
    "    f.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
